apiVersion: v1
kind: Service
metadata:
  name: forex-risk-api-service
spec:
  selector:
    app: forex-risk-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
